# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import watchdog_pb2 as watchdog__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in watchdog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WatchdogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListApplications = channel.unary_unary(
                '/artisan.watchdog.Watchdog/ListApplications',
                request_serializer=watchdog__pb2.Empty.SerializeToString,
                response_deserializer=watchdog__pb2.ApplicationStatusList.FromString,
                _registered_method=True)
        self.GetApplication = channel.unary_unary(
                '/artisan.watchdog.Watchdog/GetApplication',
                request_serializer=watchdog__pb2.ApplicationStatusRequest.SerializeToString,
                response_deserializer=watchdog__pb2.ApplicationStatusResponse.FromString,
                _registered_method=True)
        self.ListBuilds = channel.unary_unary(
                '/artisan.watchdog.Watchdog/ListBuilds',
                request_serializer=watchdog__pb2.Empty.SerializeToString,
                response_deserializer=watchdog__pb2.BuildStatusList.FromString,
                _registered_method=True)
        self.ListVerifications = channel.unary_unary(
                '/artisan.watchdog.Watchdog/ListVerifications',
                request_serializer=watchdog__pb2.Empty.SerializeToString,
                response_deserializer=watchdog__pb2.VerificationEntryList.FromString,
                _registered_method=True)
        self.GetSystemInfo = channel.unary_unary(
                '/artisan.watchdog.Watchdog/GetSystemInfo',
                request_serializer=watchdog__pb2.Empty.SerializeToString,
                response_deserializer=watchdog__pb2.SystemInfo.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/artisan.watchdog.Watchdog/ExecuteCommand',
                request_serializer=watchdog__pb2.CommandRequest.SerializeToString,
                response_deserializer=watchdog__pb2.CommandResponse.FromString,
                _registered_method=True)


class WatchdogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListApplications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBuilds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVerifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchdogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplications,
                    request_deserializer=watchdog__pb2.Empty.FromString,
                    response_serializer=watchdog__pb2.ApplicationStatusList.SerializeToString,
            ),
            'GetApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApplication,
                    request_deserializer=watchdog__pb2.ApplicationStatusRequest.FromString,
                    response_serializer=watchdog__pb2.ApplicationStatusResponse.SerializeToString,
            ),
            'ListBuilds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBuilds,
                    request_deserializer=watchdog__pb2.Empty.FromString,
                    response_serializer=watchdog__pb2.BuildStatusList.SerializeToString,
            ),
            'ListVerifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVerifications,
                    request_deserializer=watchdog__pb2.Empty.FromString,
                    response_serializer=watchdog__pb2.VerificationEntryList.SerializeToString,
            ),
            'GetSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInfo,
                    request_deserializer=watchdog__pb2.Empty.FromString,
                    response_serializer=watchdog__pb2.SystemInfo.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=watchdog__pb2.CommandRequest.FromString,
                    response_serializer=watchdog__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artisan.watchdog.Watchdog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artisan.watchdog.Watchdog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Watchdog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artisan.watchdog.Watchdog/ListApplications',
            watchdog__pb2.Empty.SerializeToString,
            watchdog__pb2.ApplicationStatusList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artisan.watchdog.Watchdog/GetApplication',
            watchdog__pb2.ApplicationStatusRequest.SerializeToString,
            watchdog__pb2.ApplicationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBuilds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artisan.watchdog.Watchdog/ListBuilds',
            watchdog__pb2.Empty.SerializeToString,
            watchdog__pb2.BuildStatusList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVerifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artisan.watchdog.Watchdog/ListVerifications',
            watchdog__pb2.Empty.SerializeToString,
            watchdog__pb2.VerificationEntryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artisan.watchdog.Watchdog/GetSystemInfo',
            watchdog__pb2.Empty.SerializeToString,
            watchdog__pb2.SystemInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artisan.watchdog.Watchdog/ExecuteCommand',
            watchdog__pb2.CommandRequest.SerializeToString,
            watchdog__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
